// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PedagioPayApiControlador.Models;

public partial class Debito
{
    public int IdDebito { get; set; }

    public long IdPassagem { get; set; }

    public string Categoria { get; set; }

    public decimal? Valor { get; set; }

    public DateTime? DhPassagem { get; set; }

    public string Concessao { get; set; }

    public string Placa { get; set; }

    public string Tag { get; set; }

    public byte? IdOsa { get; set; }

    public int? Eixos { get; set; }

    public string TokenUsuario { get; set; }

    public string Vencimento { get; set; }

    public bool? CdStatus { get; set; }

    public DateTime DhTimestamp { get; set; }

    public DateTime? PagoEm { get; set; }
}