// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PedagioPayApiControlador.Models;

public partial class PassagemPedido
{
    public long IdPassagemPedido { get; set; }

    public long? IdPassagem { get; set; }

    public long? IdPedido { get; set; }

    public short? IdConcessao { get; set; }

    public bool? CdStatus { get; set; }

    public DateTime? DhTimestamp { get; set; }
}