// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PedagioPayApiControlador.Models;

public partial class Pedido
{
    public long IdPedido { get; set; }

    public string MerchantOrderId { get; set; }

    public decimal Valor { get; set; }

    public DateTime? DhPedido { get; set; }

    public string PaymentMethodToken { get; set; }

    public string PaymentMethodTokenExpiration { get; set; }

    public byte? IdFormaPagamento { get; set; }

    public string CardBrand { get; set; }

    public string CardNumber { get; set; }

    public string TransactionId { get; set; }

    public string ProofOfSale { get; set; }

    public string AuthorizationCode { get; set; }

    public string AuthenticationUrl { get; set; }

    public Guid? PaymentId { get; set; }

    public short? IdStatus { get; set; }

    public short? ReturnCode { get; set; }

    public string ReturnMessage { get; set; }

    public int? Amount { get; set; }

    public bool? Settle { get; set; }

    public bool? Authenticate { get; set; }

    public DateTime? DhAtualizacaoStatus { get; set; }

    public DateTime? DhCancelamento { get; set; }

    public string JustificativaCancelamento { get; set; }

    public decimal? ValorRepasse { get; set; }

    public decimal? ValorTaxa { get; set; }

    public DateTime? DhRepasse { get; set; }

    public DateTime? DhAtualizacaoRepasse { get; set; }

    public bool? BlExportadoPagamento { get; set; }

    public DateTime? DhExportadoPagamento { get; set; }

    public bool? BlEnvioStatus { get; set; }

    public bool? BlExportadoStatus { get; set; }

    public DateTime? DhExportadoStatus { get; set; }

    public bool? CdStatus { get; set; }

    public DateTime? DhTimestamp { get; set; }
}