// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PedagioPayApiControlador.Models;

public partial class UsuarioCartao
{
    public int IdUsuarioCartao { get; set; }

    public string TokenUsuario { get; set; }

    public byte? IdTipoCartao { get; set; }

    public string NumeroCartao { get; set; }

    public DateTime? DhValidade { get; set; }

    public string CodigoSeguranca { get; set; }

    public string NomeCartao { get; set; }

    public string DocumentoUsuario { get; set; }

    public string MetodoPagamentoToken { get; set; }

    public DateTime? MetodoPagamentoTokenExpiracao { get; set; }

    public string MetodoTipoPagamento { get; set; }

    public string IdPagamentoEstorno { get; set; }


    public bool? BlPrincipal { get; set; }

    public bool? CdStatus { get; set; }

    public DateTime? DhTimestamp { get; set; }

    public string Bandeira { get; set; }
}